### ISSUE TITLE
Game freezes

### ISSUE THREAD

**Issue by max-radin** [bleakley/starfarer#11]
A player has reported that sometimes the game freezes (seems to be getting stuck in a loop, rather than a js error).

**Comment by bleakley** [comment]
Any more information on this?

**Comment by bleakley** [comment]
Could this have been caused by a temple event that created an anomaly in a system where all possible planet names were exhausted? In that case this is fixed by 545f19a19080fcca6c6bcc809ff3a15f37c1cd26

**Comment by bleakley** [comment]
The opening system generally has a large number of anomalies, and each one used up an available planet name, even if the name was later changed. If the opening system was using system-derived planetary names and had a high number of anomalies this would definitely have caused an infinite loop.

Because this bug is fixed, I'll close this for now.
